name: Node Setup
description: Node.js setup for CI, including cache configuration

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        run_install: false
        version: 9

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        #   cache: pnpm

    - name: show npm registry
      run: npm config get registry
      shell: bash

    - name: Install dependencies
      run: pnpm install
      shell: bash
