name: 🎉 Push Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-docker-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    if: github.repository == 'dream-num/univer-pro-sheet-start-kit'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: ./.github/actions/setup-node

      - name: Run build task
        run: |
          pnpm build

      - name: Login to Aliyun Container Registry (ACR)
        uses: aliyun/acr-login@v1
        with:
          login-server: univer-acr-registry.cn-shenzhen.cr.aliyuncs.com
          region-id: cn-shenzhen
          username: '${{ secrets.REGISTRY_USERNAME }}'
          password: '${{ secrets.REGISTRY_PASSWORD }}'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: buildx

      - name: Build and Push Docker Image (tag)
        run: |
          IMAGE_TAG=${GITHUB_REF/refs\/tags\/v/}
          make push_image NS=release PUSH_TAG=$IMAGE_TAG BUILDER=${{ steps.buildx.outputs.name }}
        if: github.event_name == 'push'

      - name: Build and Push Docker Image (workflow_dispatch)
        run: |
          IMAGE_TAG=$(echo "${{ github.sha }}" | cut -c 1-7)
          make push_image NS=release PUSH_TAG_AS_LATEST=false PUSH_TAG=$IMAGE_TAG BUILDER=${{ steps.buildx.outputs.name }}
        if: github.event_name == 'workflow_dispatch'

  build-binary:
    name: Build Binary
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: ./.github/actions/setup-node

      - uses: MOZGIII/install-ldid-action@v1
        with:
          tag: v2.1.5-procursus7

      - name: Run build task
        run: |
          pnpm build:pkg

      - name: Set version output
        id: version
        run: |
          echo "version=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_OUTPUT

      - uses: hexf00/upload-to-oss@v1
        with:
          source: .github/server/build/univer-demo-ui-win-x64.exe
          dest: releases/v${{ steps.version.outputs.version }}/binary/demo-ui.exe
          bucket: release-univer
          region: oss-cn-shenzhen
          accessKeyId: ${{ secrets.S3_ACCESS_KEY_ID }}
          accessKeySecret: ${{ secrets.S3_ACCESS_KEY_SECRET }}

      - uses: hexf00/upload-to-oss@v1
        with:
          source: .github/server/build/univer-demo-ui-macos-arm64
          dest: releases/v${{ steps.version.outputs.version }}/binary/demo-ui-macos
          bucket: release-univer
          region: oss-cn-shenzhen
          accessKeyId: ${{ secrets.S3_ACCESS_KEY_ID }}
          accessKeySecret: ${{ secrets.S3_ACCESS_KEY_SECRET }}
